apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: flask-app
  template:
    metadata:
      labels:
        name: flask-app
    spec:
      containers:
      - name: flask-container
        image: 636094856180.dkr.ecr.us-east-1.amazonaws.com/flask_app:latest
        resources:
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        envFrom:
        - configMapRef:
            name: app-config-map
